cache:
  apt: true
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade pip
  - pip install --upgrade cython
  - pip install --upgrade numpy
  - pip install --upgrade scipy
  - pip install --upgrade --editable .
  - pip freeze
language: python
notifications:
  email: false
python:
  - 2.7
sudo: false
virtualenv:
  system_site_packages: true
script:
  - python setup.py test -a -x
